name: building Golang application
on:
  push:
    branches:
      - "release/v[1-9].[0-9]+"

jobs:
  build_golang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: list filesystem before build
        run: ls -lR
      
      - name: Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAYDEPLOYTOKEN }}
          service: "CICD_Bear"
      
      - name: Test
        uses: 8398a7/action-slack@v3
        env:
          SLACK_CHANNEL: ${{ secrets.SLACKTESTINGCHANNEL }}
        with:
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD CA Submission",
                  "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* ${{ vars.NAME }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* ${{ vars.EMAIL }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* ${{ vars.MATRICULATION_NUMBER }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ vars.REPOSITORY }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ vars.DEPLOYMENT_URL }}"
                  }
                ]
              }
            ]