name: building Golang application
on:
  push:
    branches:
      - "release/v[1-9].[0-9]+"

jobs:
  build_golang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: list filesystem before build
        run: ls -lR
      
      - name: Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAYDEPLOYTOKEN }}
          service: "CICD_Bear"
      
      - name: Test Submission in Slack Channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD CA Submission",
                  "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* Nyi Nyi Htet Naing"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* konnhtetnaing@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* A0269552U"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ secrets.REPOSITORY }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ secrets.DEPLOYMENT_URL }}"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ secrets.DEPLOYMENT_URL }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Visit"
                  },
                  "value": "${{ secrets.DEPLOYMENT_URL }}",
                  "url": "${{ secrets.DEPLOYMENT_URL }}",
                  "action_id": "button-action"
                }
              }
            ]
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACKTESTINGCHANNEL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK