name: building Golang application
on:
  push:
    branches:
      - "release/v[1-9]+.[0-9]+"

jobs:
  build_golang:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: list filesystem before build
        run: ls -lR
      
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Railway Cli
        run: npm i -g @railway/cli
      
      - name: Deploy on Railway
        run: railway up
        env:
          railway_token: ${{ secrets.RAILWAYDEPLOYTOEKN }}
      
      - name: Test Submission in Slack Channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 CI/CD CA Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* Nyi Nyi Htet Naing"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* konnhtetnaing@gmail.com"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:* A0269552U"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* ${{ secrets.GIT_REPOSITORY }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.DEPLOYMENT_URL }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Visit Website",
                      "emoji": true
                    },
                    "url": "https://${{ secrets.DEPLOYMENT_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACKTESTINGCHANNEL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK